ministryofjustice/calculate-release-dates-api

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Updates gradle plugin to 3.3.5
Updates gradle to 7.1.1-bin

CVL-27: Update gradle and spring boot plugin to fix overnight Trivy scan failures

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/PrisonerDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/TestController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/TestDataIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/PrisonApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/JsonTransformation.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/TestDataControllerTest.kt
src/test/resources/application-test.yml

This adds another test endpoint so that the calculation engine can be tested via postman / the front end
Will probably only be a temporary endpoint to aid testing by the wider team until our app is more mature

CRS-170 Add endpoint to pass a JSON string to test our calculation engine - will be used for testing purposes only

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/Booking.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/Sentence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceCombinationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/resources/test_data/overall_calculation/psi-examples/38.json
src/test/resources/test_data/overall_calculation/ux-examples/1-consecutive.json
src/test/resources/test_data/overall_calculation/ux-examples/3.json

Calculation test examples I've done in the past had the wrong consecutiveUUIDs. The consecutiveUUIDs should reference the sentence that is consecutive to, I had it the other way around.

CRS-540 Fixing calcuation breakdown.

---

helm_deploy/calculate-release-dates-api/values.yaml

These keys are not required by our service any more - as we pass through the users token and this service does not require any extra roles

CRS-516 remove client id and client secret from values.yaml - had already been removed from elsewhere

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationServiceTest.kt

Publishing the event doesn't constitute a failure at the moment because we are writing back to NOMIS using a POST endpoint.
Eventually the event will be used to write back to NOMIS in an async fashion and then this will need refactoring

CRS-610 Do not propogate error if publishing the event fails - simply log it

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/CalculationRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/health/HealthCheckTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/health/InfoTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/WorkingDayControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/WorkingDayServiceTest.kt

- Principally, the Gradle-spring-boot version
- Update path to Kotlin mockito
- Overrode the equals/hashcode/toString to avoid performance warning
- Added logback at specific version to force version push from 1.2.7 to 1.2.9 to avoid a vulnerability.
- Changes to the way tests for info endpoint

CRS 659 update to latest version of plugins

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/OffenderOffence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt

PR to map nomis data to schedule 15. This should fix the failures in 1000 calcs with SDS+. This may need re-thinking if the users are going to input schedule 15.

CRS-663 mapping NOMIS data to schedule 15.

---

helm_deploy/values-preprod.yaml

NOMIS are using the first of April as the pcsc commencement date for testing. Updating to match that so we can compare calculations.

Updating config to match NOMIS

---

.circleci/config.yml
.spectral.yml
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/AdjustmentDuration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ReleaseDateCalculationBreakdown.kt
src/main/resources/application-dev.yaml
src/main/resources/application-docs.yml

This is a proof of concept for adding GDS linting into the pipeline.
Added jobs:
1. generate the api doc. This uses the gradle plugin https://github.com/springdoc/springdoc-openapi-gradle-plugin
The main issue I had here is that in order to generate the openapi file the plugin needs to spin up the spring boot service. So I've copied the configuration for running spring tests by running the service against h2. The ugly part of this is including h2 as a `implementation` rather than `testImplementation`. This is done with a gradle property so that its not included on the main build. I'm open to any other suggestions, I couldn't figure out how to run the app with test dependencies.
2. lint the api doc. This is configured in the `.spectral` file.
As expected the build fails and circle ci …

Crs 1052 POC for GDS linting in circle ci pipeline.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/FixedTermRecallDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/PrisonApiMockServer.kt

Light touch refactor to replace prison-api call  to return-to-custody-date .
More could be done with this; ideally the ReturnToCustodyDate object should be replaced with FixedTermRecallDetails, however there is quite a lot of change required for this (UI and API). It is being persisted to a database JSON column  and then resurfaced in an endpoint, hence went for the light touch approach for now

CRS-1087 Replace return-to-custody prison-api endpoint call (deprecated) with  fixed-term-recall call

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingServiceTest.kt

Validation is not required by the view journey as we are just displaying a previous calc. This change also removes the validation call from the get-breakdown call.
Additionally, if we add new validation rules there is a potential for the view journey to break, because it calls validation using old input data (potentially).. and the old input data could break the validation if there are new rules.

CRS-1101 Remove validation call from the get-calc-breakdown endpoint, this is unnecessary and causes problems for the view journey

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/UnusedDeductionCalculationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/unuseddeductions/controller/UnusedDeductionsController.kt

This PR adds an endpoint to the unused deductions that will only calculate the unused deductions. The updating of adjustments functionality will be removed from calculate release dates and be handled by the new unused deductions listener where the changes are handled with sqs queues instead.

ADJUST1-276 Unused deductions infrastructure.

---

README.md
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/WebClientConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/PcscMarkers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSdsPlusLookupService.kt
src/main/resources/application-dev.yaml
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/ManageOffencesMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ManualCalculationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/MoPCSCIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSdsPlusLookupServiceTest.kt
src/test/resources/application-test.yml

* Adds new service that sets Offence markers based on response from Manage Offences `schedule/pcsc-indicators?<offence-codes>` endpoint

CP-1670 Add Service to lookup PCSC Markers from MO API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/SentenceCalculationType.kt

* Production issue where sentence type was one that had not been seen before in CRDS.
* Added missing type to ENUM

Bug Fix - Prod Issue of missing sentence type

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ComparisonOverview.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/ComparisonPersonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt

* Some calculated HDCED4+ results were not being returned due to the rep query, they are now returned in a seperate result list.

CRS-1788 Fix issue with not all HDC4+ not being shown in the list

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonServiceTest.kt

Was taking the latest across any person instead of valuation outcomes per person.

CRS-1811: match up valuation outcomes with people on HDC4+ mismatches

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt
src/test/resources/test_data/api_integration/sentences/CRS-1634-no-offence-end-date.json
src/test/resources/test_data/api_integration/sentences/CRS-1634-no-offence-start-date.json

* Add new controller endpoint for manual entry verification (Currently only validates the offence dates so that it can be successfully submitted back to NOMIS)
* Made the validation more understandable
* Bump the Jacoco plugin version to remove the sea of red when running tests

CRS-1634 Add verification for manual entry submission

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculationOriginalData.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/DetailedCalculationResults.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/DetailedCalculationResultsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/DetailedCalculationResultsServiceTest.kt

Minor model change to show that prisoner detail and sentence and offence information is that which was used to make the calculation and is not current.

CRS-1848: Show that prisoner detail and offences are historic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/LatestCalculation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/OffenderKeyDates.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClientIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonServiceTest.kt

Remove use of map and just use a list as this is to present all dates rather than pick specific dates. This preserves the order of dates as well. Make calculatedAt mandatory in line with latest prison API.

CRS-1849: Latest calc model changes

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/LatestCalculation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationServiceTest.kt

This is required to be able to link into the view journey which requires prisoner id and booking id.

CRS-1849: Add booking id to latest calc API

---

helm_deploy/values-prod.yaml

* Apply pod memory limit bump that was made on preprod to prevent bulk calc pods from being culled when they reached the 1GB limit.

Bump Prod pod mem limits

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationServiceTest.kt

Was showing SLED, LED and SED all at once. Only show the SED and LED if they are not the same or are missing. If they are the same only show SLED.

CRS-1849: hide SED and LED if we can create a SLED

---

.circleci/config.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

* Update slack channels used for alerting and notification of deployments to the legacy specific ones

CRS-1859 Update config to use new alerting channels for legacy

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationResultEnrichmentService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationResultEnrichmentServiceTest.kt

When a HDCED falls on a weekend or bank holiday the weekend adjustment hint text should show the date of the next working day. Other date types remain on previous working day.

CRS-1882: HDCED hint should use next working day instead of previous

---

src/main/resources/migration/common/V50__extend_length_of_user_fields.sql

Username can by up to 240 according to hmpss-auth schema. In reality, it will probably not be this big as it should only be a staff id for NOMIS users or a UUID for systems however custom users can be created such as CRD_TEST_USER which breaks the usual pattern.

CRS-1794: make all username fields 240 chars

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/HistoricCalculation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/NomisCalculationSummary.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationResultEnrichmentService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HistoricCalculationsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenderKeyDatesService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/HistoricCalculationsControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/LatestCalculationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenderKeyDatesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClientIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonServiceTest.kt

This update is necessary to present historical NOMIS calculations to the front-end application - Calculate Release Dates App. - https://dsdmoj.atlassian.net/browse/CRS-1877
Details of the Changes:  
1. The /historicCalculations endpoint in CRDAPI is utilized to display the history records of NOMIS and CRD Calculations.
The offenderSentCalculationId is added to the response, enabling the front-end to call the CRD-Api to fetch the corresponding NOMIS record for NOMIS entries.
2. The /calculation/nomis-calculation-summary/{offenderSentCalculationId} endpoint is introduced to fetch the NOMIS Record from the Prison API. 
This endpoint has been added and merged in this PR and is deployed to Dev - https://github.com/ministryofjustice/prison-api/pull/2110
3. A minor refactoring in …

Display Past Nomis Calculations on Calculate release dates app

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/AnalyzedSentenceAndOffences.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/PrisonApiDataVersions.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/SentenceAndOffences.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSdsPlusLookupService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceAndOffenceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSdsPlusLookupServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceAndOffenceServiceTest.kt

Add new flag on sentence to show its SDS plus. This should replace the use of individual offence level indicators in a future change.

CRS-1940: Indicate SDS+ status at sentence level

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/SDSEarlyReleaseExclusionForOffenceCode.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSDSReleaseArrangementLookupService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/ManageOffencesMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesApiClientIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSDSReleaseArrangementLookupServiceTest.kt

Wrong value used for no match from manage offences. Should be NONE but was NO

CRS-1942: Fix SDS early release exclusion markers

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceAndOffenceService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceAndOffenceServiceTest.kt

When you have multiple offences to a sentence and it is not the same as previous calculation then the normalised sentences were being lost.

Fix multiple offences to sentence analysed output

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/util/BookingHelperTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt

https://dsdmoj.atlassian.net/browse/CRS-1937.
This PR addresses the calculation of ESL for manual entry journey and saves that to NOMIS after converting to Years Months and Days. When there is Indeterminate sentences or absence of SED then the release date is set to 0 Years, 0 Months and 0 days

Add logic to calculate ESL for Manual Release date entries

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SentenceCalculation.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-ac1.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-ac2.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-ac3.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-ac4.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-ac5.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-botus-unaffected-by-remand.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1943-botus-unaffected-by-tagged-bail.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-ac1.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-ac2.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-ac3.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-ac4.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-ac5.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-botus-unaffected-by-remand.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1943-botus-unaffected-by-tagged-bail.json

Creates the unit tests from the tickets plus a couple of others to check that taggged bail and remand are not applied to Botus sentences (this was noticed whilst testing the rest of the Botus work)

Crs 1943 Botus tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonServiceTest.kt

We were combining all sentences and offences and doing a single lookup which could produce too many offences and make the MO URL too long.

Fix bulk comparison with SDS exclusion lookup

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/Booking.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculationOptions.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationBreakdownService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/RelevantRemandService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceIdentificationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/unuseddeductions/service/UnusedDeductionsCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/JsonTransformation.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationBreakdownServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceCalculationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceIdentificationServiceTest.kt

Moved the calculate ersed flag and SDS early release flag into their own options object to be passed around for calcluation. This allows modification of the options for recalculation for SDS4x as well as improves cohesion of booking object.

Extract calculation options from booking and feature toggles

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Hdced4Calculator.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/overall_calculation/custom-examples/crs-1981-ac1.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1981-ac2.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1981-ac3.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1981-ac1.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1981-ac2.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1981-ac3.json

Apply remand and tagged bail to the SDS+ notional CRD before calculating HDCED4+. This is to ensure that it is not before the CRD of the SDS+ sentences.

CRS-1981: HDCED4+ SDS+ consec chain fix for remand and tagged bail

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingExtractionService.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/overall_calculation/custom-examples/crs-1997-ac1-hdc-eds-concurrent-sds.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1997-ac2-hdc-eds-concurrent-sds.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1997-ac3-hdc-sopc-consec-sds.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1997-ac4-hdc-eds-consec-sds.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-1997-ac5-hdc-sopc-consec-sds.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1012-hdc-for-eds-sopc-ac4.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1997-ac1-hdc-eds-concurrent-sds.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1997-ac2-hdc-eds-concurrent-sds.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1997-ac3-hdc-sopc-consec-sds.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1997-ac4-hdc-eds-consec-sds.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-1997-ac5-hdc-sopc-consec-sds.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-876-eds-sds-ac15.json

* Enables HDCED to be generated for chains that have EDS/SOPC in them, when it was previously omitted from the results.

CRS-1997 Stop preventing HDCED when there are  EDS/SOPC sentences

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ConsecutiveSentence.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt

* Add support for A/Fine sentences in Consecutive Sentences
* Update test to ensure bookings with consec A/Fines can have manual calcs submitted.

CRS-2012 Add AFine support for consecutive sentences

---

.circleci/config.yml
build.gradle.kts
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationIntTest.kt

https://dsdmoj.atlassian.net/browse/CRS-2096
Have set code coverage to fail if the coverage is below 80%

CRS-2096 Adding UT code coverage

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Tranche.kt
src/test/resources/test_data/calculation-sds-early-tranching.csv
src/test/resources/test_data/overall_calculation/tranches/crs-2121_2.5_plus_2.49.json
src/test/resources/test_data/overall_calculation/tranches/crs-2121_2x2.5.json
src/test/resources/test_data/overall_calculation/tranches/crs-2121_4x1_plus_0.9.json
src/test/resources/test_data/overall_calculation/tranches/crs-2121_5x1.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2121_2.5_plus_2.49.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2121_2x2.5.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2121_4x1_plus_0.9.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2121_5x1.json

Initial version of the fix, for @Sean to review
Apply the totalduration based on the concurrent sentence start date of the previous sentence. This adds a single day for each new sentence.
A further test case will be added for several sentences reaching 5 years

Fix for multiple sentences boundary issue

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SDSEarlyReleaseDefaultingRulesService.kt
src/test/resources/test_data/calculation-sds-early-tranching.csv
src/test/resources/test_data/overall_calculation/tranches/crs-1871_ftr_consec.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-1871_ftr_consec.json

Small tweak to how the defaulting service identifies whether a date… is before the tranche (if it comes only from the 50%)

Identify HDCED dates from before commencement that only come from 50% release

---

helm_deploy/values-alt-dev.yaml
src/main/resources/application-alt-4-calculation-params.yml

* Enable testing of changes for CRS-2126 by setting T1 commencement to current date

CRS-2126 Testing - set alt-dev to have T1 commencement date of (today)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheAllocationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheAllocationServiceTest.kt
src/test/resources/test_data/calculation-sds-early-tranching.csv
src/test/resources/test_data/overall_calculation/tranches/crs-2105-rwe-1.json
src/test/resources/test_data/overall_calculation/tranches/crs-2105-rwe-2.json
src/test/resources/test_data/overall_calculation/tranches/crs-2105-rwe-3.json
src/test/resources/test_data/overall_calculation/tranches/crs-2105-rwe-4.json
src/test/resources/test_data/overall_calculation/tranches/crs-2105-rwe-5.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2105-rwe-1.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2105-rwe-2.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2105-rwe-3.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2105-rwe-4.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2105-rwe-5.json

* Amend to match criteria of ALL SDS getting tranche allocated where when applicable regardless of exclusions
* Ensure that recalls prior to T1 are not considered as early release, pending future ticket to better assess TUSED of original sentence based on movements.

CRS-2105 fixes

---

src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/JsonTransformation.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HintTextTest.kt
src/test/resources/test_data/hint-text.csv
src/test/resources/test_data/hint-text/expected-results/ped-hints.json
src/test/resources/test_data/hint-text/input-data/ped-hints.json

This does more of an end-to-end test of hints, so the expected results are effectively what you'd see on the UI; e.g.
```
[
{
"type": "SLED",
"date": "2029-09-14",
"hints": []
},
{
"type": "CRD",
"date": "2026-09-14",
"hints": []
},
{
"type": "PED",
"date": "2024-10-12",
"hints": [
"Friday, 11 October 2024 when adjusted to a working day",
"50% date has been applied",
"PED adjusted for the CRD of a concurrent sentence or default term",
"The post recall release date (PRRD) of Tuesday, 18 March 2025 is later than the PED"
]
},
{
"type": "ESED",
"date": "2029-09-14",
"hints": []
}
]
```

CRS-2157 Add Test capability to allow for a more end-to-end test of hint-texts

---

src/test/resources/test_data/hint-text.csv
src/test/resources/test_data/hint-text/expected-results/ped-hints.json

This test was failing on Friday (11 Oct 2024) because the release date of the prisoner was 12 Oct 2024 (in the future on a Saturday) - so the 'non working day' logic was being applied and a hint saying release him on Friday was shown
But now the release date is in the past, so the hint will never be shown going forward (as per the logic in the code)

CRS-2157 fix failing test - fridaty release date is not applicable if release date is in the past

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/RecallValidationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/UnsupportedSDS40RecallSentenceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt

Update validation criteria for recall sentences based on tranche commencement date
- Add a condition to fire a validation message only for recall sentences sentenced before the tranche commencement date. Sentences after this date will no longer cause the error to appear.
- Move relevant tests for this exception to a separate file for better organization.
- Add two new tests to cover scenarios where sentences are before and after the tranche commencement date.

Update validation criteria for recall sentences based on tranche commencement date

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/AdjustmentValidationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/unuseddeductions/controller/UnusedDeductionsControllerIntTest.kt
src/test/resources/test_data/overall_calculation/validation/CRS-2082.json

+ change how the range of sentences is determined (relates to fixing CRS-2082)
TODO Add explicit TDD's for the scenario in the ticket
(not done yet as the final release dates after the calculation finishes dont match the ticket, that will be investigated next)

CRS-2162 The validation for the overlapping-remand-logic should use the adjustedDeterminateReleaseDate (rather than unadjusted)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingCalculationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt

* Allow manual calc to not use the uninitialised sentence calc when constructing sentences for ESL purposes
* Catch any errors resulting in ESL generation and set ESL to 0

CRS-2174 Fix issue with manual calc and sentence construction

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/RecallValidationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
src/test/resources/test_data/calculation-validation-examples.csv
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac1.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac2.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac3.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac4.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac5.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac6.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac7.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2145-ac8.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2145-ac1.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2145-ac2.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2145-ac3.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2145-ac4.json

- Add test cases for ACs
- Amend the validation framework for scenarios where the validation means no dates are known
- Add a log message for the sentence that would be excluded
@scott-lace-moj  - some tests not producing expected date values

CRS-2145 - TUSED producing recalls imposed on or after 2024-09-10 should be supported

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/PersonComparisonJson.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/ComparisonPersonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ComparisonController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonService.kt

New endpoint to expose underlying JSON data related to person comparison.
Data includes inputData, sentenceAndOffences and adjustments.
Remove unused method  findByComparisonIdIsAndHdcedFourPlusDateIsNotNull from ComparisonPersonRepository.

CRD-2182-view-json-person-comparison

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt

Comparisons can sometimes contain DTO_RECALL validation codes. This was previously removed as its no longer needed.
It can still be used when indirectly parsing historic data.

CRS-2190-add-dto-recall-enum

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/ToDoType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ThingsToDo.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ThingsToDoController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ThingsToDoService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ThingsToDoServiceTest.kt

this is as part of some work in CCARD, to display a list of TODO's in every service
This is the initial placeholder endpoint and is subject to change depending on what the TODO item needs to display

CMG-182 Add things-to-do endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/timeline/TimelineUalAdjustmentCalculationHandler.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/calculation_breakdown_response/hdc4/crs-2159-prisoner-1.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2210-concurrent-recall-ual-timeline-bug.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2210-concurrent-recall-ual-timeline-bug.json

Bug where UAL occurs before the overall CRD. but after a concurrent CRD. UAL should only apply to the concurrent sentence if its a recall and shouldn't affect its original determinate release date.

CRS-2210 Fixing bug with concurrent UAL license recalls.

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SDSEarlyReleaseExclusionType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/manageoffencesapi/SDSEarlyReleaseExclusionForOffenceCode.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSDSReleaseArrangementLookupService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/timeline/handlers/TimelineCalculationHandler.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-1.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-2.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-3.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-4.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-5.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-6.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-7.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac1-8.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac2-1.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac2-2.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac2-3.json
src/test/resources/test_data/overall_calculation/tranches/crs-2202-ac3-1.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-2.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-3.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-4.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-5.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-6.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-7.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac1-8.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac2-1.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac2-2.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac2-3.json
src/test/resources/test_data/overall_calculation_response/tranches/crs-2202-ac3-1.json

Produce tests for recall sentences affected by tranche3 offences.
Remove unnecessary MURDER exclusion type.
Remove complex method comments for multiplierFnForDate, which is being replaced in upcoming changes.

CRS-2202-tranche3-recalls

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingExtractionService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HdcedExtractionService.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/overall_calculation/custom-examples/crs-2211-non-ora.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2211.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2211-non-ora.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2211.json

- Updated `HdcedExtractionService` to suppress HDCED when it is equal to or later than CRD/ARD, ensuring compliance with AC1.
- Added utility methods `latestAdjustedReleaseDateIsAfterHdced` and `releaseDateIsAfterHdced` for precise HDCED handling.
- Modified `BookingExtractionService` to prevent HDCED display or submission under the specified conditions.
- Added test cases for CRS-2211 and CRS-2211-non-ora to validate the suppression logic.
- Included relevant test data reflecting adjustments and expected outcomes, ensuring scenarios like ADAs are correctly processed.

Suppress HDCED if equal to or later than CRD

---

helm_deploy/calculate-release-dates-api/values.yaml

Increase memory limit to 4Gb in light of larger DB size.
A more optimised solution will be added in due course to prevent future memory issues.

CRS-2240-data-analytics-extractor-memory-limit

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SDSPlusCheckResult.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ReleaseArrangementLookupServiceTest.kt

Fix issue where items on List D (over 7 years) use the SDS+ date, rather than the PCSC date 
Note: this, sadly, introduces a dependency between lists and date ranges we have tried to seperate as much as possible within code. There doesn't seem to be an obvious way around that :(

Add test to cover list D excluded scenarios

---

src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HintTextTest.kt
src/test/resources/test_data/hint-text/expected-results/crs-2164-ac3.json
src/test/resources/test_data/hint-text/expected-results/crs-2218-ac01.json
src/test/resources/test_data/hint-text/expected-results/crs-2218-ac02-1.json
src/test/resources/test_data/hint-text/expected-results/crs-2218-ac03-1.json

this changes some of the hints because the variable one 'The Discretionary..' will no longer show (the condition has been mocked to return false every time)

CRS-2254 Mock call to nonFridayReleaseService to avoid hint texts changing over time in the tests

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingExtractionService.kt

Possibly some tech debt here because there are no integration/TDD tests that test this functionality via the full-validation route

CRS-2260 Add null check for TUSED breakdown - could be null via the full-validation route when a BOTUS exists

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/exceptions/MissingTermException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt

Refactor transform function to return StandardDeterminateSentence as the default sentence type.
mpoThrow exception if no imprisonmentTerm or licenceTerm is present for ExtendedDeterminateSentence or SopcSentence

crs-2284-sentence-type-resolution

---

src/main/resources/migration/postgres/V66__add_primary_key_to_approved_dates_submission_approved_dates.sql

approved_dates_submission_approved_dates doesn't have a primary key - add auto incremented id column

crs-2262-crs-2292-add-primary-key-approved-dates

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationBreakdownService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiDataMapper.kt
src/test/resources/test_data/hint-text.csv
src/test/resources/test_data/hint-text/expected-results/crs-2317-single-botus.json
src/test/resources/test_data/hint-text/input-data/crs-2317-single-botus.json

Provide historic TUSED data to sentence mapper before performing calculationWithBreakdown.

crs-2317-missing-historic-tused-for-breakdown

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/ComparisonStatusValue.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonEventPublisher.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonEventService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClient.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ComparisonEventIntTest.kt

1. Increase timeout for getting prisoners at establishment.
2. Bulk message request only allows 10 messages at a time
3. Add new state for SETUP.
4. Mark comparison as error if exception happens in the setup

Improving bulk comparison

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationService.kt
src/test/resources/test_data/calculation-service-examples.csv
src/test/resources/test_data/overall_calculation/consecutive-sentences/crs-2283-ac5-5.json

Check for none Consecutive sentences with consecutiveSentenceUUIDs.
Such sentences have likely been removed from an earlier consec sentence to avoid duplicates consec chains.
If the UUID is present for any current consec sentence chain, the sentence has more than one child  .

Crs 2283 removed duplicate consec sentences

---

helm_deploy/calculate-release-dates-api/values.yaml

* Extract failed on Wed morning due to CPU limits, it did pass again the following day however the CPU was throttled due to the initial request being fairly low but within limits

Set the CPU request limit to 1 so CPU isn't overly throttled

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ManualCalculationIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
src/test/resources/test_data/api_integration/sentences/CRS-2333-1.json
src/test/resources/test_data/api_integration/sentences/CRS-2333-2.json
src/test/resources/test_data/reset-base-data.sql

Store post calculation validation errors resulting in manual journey.
Errors can be from pre-calculation or post-calculation.

crs-2333-add-post-calc-manual-journey-reasons

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculableSentence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingExtractionService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceIdentificationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceIdentificationServiceTest.kt
src/test/resources/test_data/overall_calculation/custom-examples/crs-2339-1.json
src/test/resources/test_data/overall_calculation/custom-examples/crs-2339-2.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2339-1.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2339-2.json
src/test/resources/test_data/sentence/two_day_2018_mar.json

One day standard determinate sentences should only have SED and ARD in place of SLED and CRD.

Crs 2339 one day sentences

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt

Ignore CONCURRENT_CONSECUTIVE_SENTENCES for bulk calc. Validation does not prevent calculations and is used for informational purposes.

crs-2351-bulk-calc-validation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationIntTest.kt
src/test/resources/test_data/api_integration/prisonapiadjustments/CRS-2338.json
src/test/resources/test_data/api_integration/sentences/CRS-2338.json

Add validation where a consecutive chain contains an inactive sentence.

crs-2338-inactive-consec-chain

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationServiceTest.kt

Fix validation for multiple offences assigned to single sentence. Sentence must be consecutive to another.

crs-2353-bulk-validation-fix

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/RecallType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/UnadjustedReleaseDate.kt

- Refactored UnadjustedReleaseDate to use when-expression over recall types.
- Consolidated fixed-term logic via lengthInDays property.
- Added explicit error handling for unsupported or missing recall types.
- Added FIXED_TERM_RECALL_56 (56-day) to RecallType enum.

refactor recall release date logic

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/PreCalculationValidationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/UnsupportedValidationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt

Displays a validation message when offence code CL77036 is used in a sentence,
instructing the user to replace it with the appropriate underlying offence code
ending in 'C'. This prevents national security and other excluded offences from
being miscategorised and incorrectly included in SDS-40 eligibility.
followed by a small refactor:
Replaces individual validation methods for unsupported offence codes with a
single map-driven approach. This simplifies future additions and reduces
duplication. Logic for SC070xx, PH97003, CL77036, and suspended offences is
now configured via a predicate-to-ValidationCode map.
Also updates PreCalculationValidationService to use the unified method.

Crs 2066 block conspiracy offence

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationType.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationIntTest.kt
src/test/resources/test_data/api_integration/sentences/CRS-2370.json

Ignore CONCURRENT_CONSECUTIVE validation messages when confirming calculation.
The validation type is informational rather than preventing a calculation.
Future refactoring should resolve such ambiguity.

crs-2370-booking-data-error

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HdcedCalculator.kt
src/test/resources/test_data/overall_calculation/hdc-365/crs-2386-ac9.json
src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2343.json
src/test/resources/test_data/overall_calculation_response/hdc-365/crs-2386-ac9.json

Further changes to the rules regarding UAL have been made, the 3rd calculation including UAL was not required as we only need to exclude UAL for any case where we default to the sentence date + 14 days.
Now the rules are as follows:
Step 1: Calculate HDC180 & HDC365 with Remand & TB If date falls before SD + 14, default to SD + 14 days for both HDC180 & HDC365
Step 2: Apply applicable UAL to calculated HDC180 and HDC365 dates
Step 3: Follow one of the following:
3a: If HDC180 falls before 03/06/2025 - Retain HDC180
3b: If HDC365 falls after 03/06/2025 Retain HDC365
3c: If HDC180 falls after 03/06/2025 and HDC365 is before 03/06/2025 Default to 03/06/25
Step 4: Apply ADAs & RADAs
Step 5: Defer any HDCED to later PRRD, PED, CRD, ARD of other sentences

CRS-2386: Update HDC rules regarding UAL (part 2)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt

We were loading the booking even if there were unsupported sentences. The booking load checks has failsafes to ensure validation has been called and throws an exception. We were already returning if there were unsupported sentence or calculation messages so just moved the loading of the booking after that.
Also added some tests.

CRS-2401: Fix issue with unsupported sentences

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationResultEnrichmentService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/TestUtil.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/calculation/CalculationExampleTests.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HintTextTest.kt
src/test/resources/test_data/hint-text/expected-results/crs-2439-ac1-hint-text.json
src/test/resources/test_data/hint-text/expected-results/crs-2439-ac2-hint-text.json
src/test/resources/test_data/hint-text/expected-results/crs-2439-ac3-hint-text.json
src/test/resources/test_data/hint-text/expected-results/crs-2439-ac4-hint-text.json
src/test/resources/test_data/hint-text/expected-results/crs-2439-ac5-hint-text.json
src/test/resources/test_data/hint-text/input-data/crs-2439-ac1-hint-text.json
src/test/resources/test_data/hint-text/input-data/crs-2439-ac2-hint-text.json
src/test/resources/test_data/hint-text/input-data/crs-2439-ac3-hint-text.json
src/test/resources/test_data/hint-text/input-data/crs-2439-ac4-hint-text.json
src/test/resources/test_data/hint-text/input-data/crs-2439-ac5-hint-text.json

When the ERSED has been defaulted to the ERS30 commencement date we should not display the SDS40 hint text "40/50% date has been applied".
Fixed a couple of tests runners that did not apply the feature toggles as per the input json.

CRS-2439: Suppress SDS40 hint text for ERS30 defaulting

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/prisonapi/BookingAndSentenceAdjustments.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/prisonapi/BookingAndSentenceAdjustmentsTest.kt

Fix for remand and tagged bail adjustments old style adjustments upgrade to AdjustmentDTO. The types were not mapped.

CRS-2449: Fix recall adjustments upgrade

---

src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/GenuineOverrideRequest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/GenuineOverrideIntTest.kt

Should have been a nullable type on the request object.

CRS-2414: Fix genuine override with no further detail
