- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/TestController.kt
> Fixed the issues with the syntax that caused the check

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenderSentenceProfileCalculationService.kt
- src/test/resources/test_data/overall_calculation/psi-examples/17.json
- src/test/resources/test_data/overall_calculation_response/17.json
- src/test/resources/test_data/psi_examples.csv
Slight refactor in how expiry dates are extracted
> Add in Example 17 data

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/exceptions/CannotMergeSentencesException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/Duration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/Sentence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenderSentenceProfileCalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceCombinationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SentenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationServiceTest.kt
- src/test/resources/test_data/overall_calculation/psi-examples/20.json
- src/test/resources/test_data/overall_calculation_response/20.json
- src/test/resources/test_data/psi_examples.csv
- Implement the Example 20 tests
- Replace aggregate with combine
- Append all
> CRS-131 Implement Example 20 test

- src/test/resources/test_data/overall_calculation/psi-examples/21.json
- src/test/resources/test_data/overall_calculation_response/21.json
> CRS-132 Implement Example 21 Test

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/CalculationOutcome.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/CalculationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/CalculationOutcomeRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/CalculationRequestRepository.kt
- src/main/resources/migration/common/V11__calculation_request_and_outcome.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/resources/application-test.yml
Also:
- Changed alerts channel to farsight-alerts
- Added a upgrade command into Dockerfile as advised by devops
TODO
- Populate calculation requests and results to the new tables
- add tests to check the population
> CRS-280 Create data model for calcultion-request and response + create JPA classes and fix int tests

- build.gradle.kts
- docker-compose-test.yml
- docker-compose.yml
- helm_deploy/calculate-release-dates-api/values.yaml
- run-local.sh
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/DomainEventPublisherConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/DomainEventsJmsConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/CalculationStatus.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/DomainEventPublisher.kt
- src/main/resources/application-localstack.yml
- src/main/resources/application.yml
- src/main/resources/migration/common/V13__make_columns_bigger.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationServiceTest.kt
- src/test/resources/application-test.yml
- src/test/resources/localstack/setup-queue.sh
This was mainly copied from another project that publishes events to the domain-events topic - see the following PR for their code
https://github.com/ministryofjustice/hmpps-restricted-patients-api/pull/46
> CRS-273 Initial work for publishing an event to the domain-events topic to notify of a confirmed release dates change

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/Duration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/DurationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SentenceTest.kt
- src/test/resources/test_data/calculation_breakdown_response/ux-examples/1-concurrent.json
- src/test/resources/test_data/calculation_breakdown_response/ux-examples/1-consecutive.json
Removing 0's from display of durations and pluralising the units.
> CRS-592 fixing display of duration.

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt
This currently only writes CRD, SED and LED. The prison-api endpoint is still WIP and wil add tthe other dates as we progress
> CRS-550 make call to prison-api to write release dates back to NOMIS

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/ControllerAdvice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/exceptions/UnsupportedSentenceException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SentenceType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SupportedSentence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ImportantDates.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/CalculationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/PrisonApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceValidationServiceTest.kt
Validate unsupported sentences.
> CRS-466 unsupported sentence errors.

- helm_deploy/calculate-release-dates-api/Chart.yaml
- helm_deploy/values-preprod.yaml
As per this guide https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live-ingress-annotation.html#add-external-dns-annotations-to-your-ingress-resource-in-live-1
> CRS-516 Add external dns annotations for preprod - as advised by CP team

- build.gradle.kts
> CRS-635 Critical vulnerability with Log4J 

- build.gradle.kts
> Version updates for a couple of areas:

- build.gradle.kts
Fix a tomcat dependency check issue with a beta version of the gradle plugin
> Update package version to the beta

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/ResourceServerConfiguration.kt
Hopefully, you can see that the lines in these files match. I just wanted to remove a deprecation warning.
> Update to the new Security DSL syntax

- helm_deploy/values-prod.yaml
it's already switched on in preprod
> CRS-1066 Turn on AFINES in prod

- helm_deploy/calculate-release-dates-api/values.yaml
See https://mojdt.slack.com/archives/C030HNP4PSP/p1658331272113449 for more context
> CRS-1068 Switch to v1.2 ingreass controllers (with no downtime)

- .trivyignore
- Dockerfile
- build.gradle.kts
Holding back Spring JMS/Java Messaging Lib because it is a bigger change
> Update various packages to the latest versions.

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/RelevantRemand.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/RelevantRemandCalculationRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/RelevantRemandCalculationResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/RelevantRemandService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationIntTest.kt
- src/test/resources/test_data/api_integration/adjustments/RELREM.json
- src/test/resources/test_data/api_integration/sentences/RELREM.json
Adding endpoint to be used by the relevant remand tool.
> MDWFP-73 adding relevant remand endpoint.

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SentenceCalculation.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationIntTest.kt
- src/test/resources/test_data/api_integration/adjustments/RELREMI.json
- src/test/resources/test_data/api_integration/sentences/RELREMI.json
Fixing issue where there is too much relevant remand
> MDWFP-114 fix an issue with the relevant remand calculation.

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/Comparison.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/ComparisonPerson.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/CaseLoadFunction.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/CaseLoadType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CaseLoad.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/ComparisonInput.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/ComparisonPersonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/ComparisonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ComparisonController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ServiceUserService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/main/resources/migration/common/V22__add_comparison.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ComparisonControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
- Add Comparison, Comparison Person, Case Load
- Create a new database model and reflect that in the input data
- Move the security context into a service to be implemented once and extended appropriately. It requires a few test changes
> Create some new endpoints and database structures for Comparisons:

- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
+ add serviceAccountName for prod
> CRS-1529 Increase number of pods in preprod and prod from 2 to 4

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/CalculationReason.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/repository/CalculationReasonRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationReasonController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationReasonControllerTest.kt
* Create and test an endpoint to return active calculation reasons.
> CRS-1748 Backend | Create endpoint to supply reasons for the frontend

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculatedReleaseDates.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationReferenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt
* Added the reason the to CalculatedReleaseDates so that it can be displayed in the view journey.
* Updated the tests to reflect this change.
> CRS-875 Display reason for calculation in the view journey

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/entity/ComparisonPerson.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ComparisonMismatchSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ComparisonPersonOverview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BulkComparisonServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonServiceTest.kt
Reverts ministryofjustice/calculate-release-dates-api#557
Changes to the db need to be considered
> Revert "Crs 1785: Make the typescript generation work"

- run-local.sh
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ComparisonMismatchSummary.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ComparisonPersonOverview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualComparisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt
* Transformation is now carried out on the DTO object
> ComparisonMismatchSummary now returns ValidationMessages

- Dockerfile
- helm_deploy/calculate-release-dates-api/values.yaml
* Bump max heap to deal with bulk comparison
> Bump Java max heap to 4G

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/DateTypeDefinition.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ReferenceDataController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ReferenceDataControllerTest.kt
API to supply the release date types and their descriptions to the front end.
> CRS-1847: Reference data API

- helm_deploy/values-alt-dev.yaml
* Update to use the dev service account name for running helm / access to K8
> CRS-1883 Try the dev ServiceAccountName

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/exceptions/CouldNotGetMoOffenceInformation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculationUserInputs.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationUserQuestionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesApiClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSdsPlusLookupService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/ManageOffencesMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationUserInputIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/MoPCSCIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSdsPlusLookupServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonServiceTest.kt
* Update OffenceSDSPlusLookupService to set offence flags
* Remove code for calculation questions
> CRS-1644 Remove CalculationQuestions

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceAdjustedCalculationService.kt
- src/test/resources/test_data/calculation-service-examples.csv
- src/test/resources/test_data/overall_calculation_response/alternative-release-point/9.json
* ERSED was previously not being recalculated post group adjustments taking effect
* Add alt scenario 9 to test list
> Allow ERSED to be recalced post timeline walk

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ComparisonPersonOverview.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualComparisonService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ComparisonServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualComparisonServiceTest.kt
SDS+ matches in bulk comparison were failing to parse after the SDS+ refactor
> CRS-1940: Fix issue with bulk comparison

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculableSentence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
Formatting of transformfunctions to use when syntax Simplifying the if as both sides appear to be identical
> Formatting of getReleaseDateType to match the rest of the file

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/OffenceSDSReleaseArrangementLookupServiceIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManageOffencesApiClientIntTest.kt
- Switch to an exception that extends RuntimeException
- Add integration tests
> Improve test coverage for Manage Offences retries

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/WebClientConfiguration.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClient.kt
- src/main/resources/application.yml
CRS-1995 Move the BulkComparison to use the system clients credentials.
HAAR have added RELEASE_DATE_MANUAL_COMPARER role to all the system clients see https://dsdmoj.atlassian.net/browse/HAAR-2716
> CRS-1995 Move the BulkComparison to use the system clients credentials.

- helm_deploy/values-alt-dev.yaml
- src/main/resources/application-alt-hdc4.yml
* Turn of sds4x in alt-dev
* Set hdc4 commencement date in the past
> CRS-1817 Make alt dev use normal calc params

- helm_deploy/values-alt-preprod.yaml
* Update alt preprod to use normal calc params
* Set hdc4 commencement date in the past
> CRS-1817 Update alt-preprod to use normal calc params

- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/resources/application-test.yml
* Temp change pending PR to remove date switch
> Temporary Fix Tests now HDC4+ commencement has passed

- src/main/resources/migration/common/V54__amend_calcReason_HDC_to_HDCAD.sql
https://dsdmoj.atlassian.net/browse/CRS-1993
> CRS-1993 Update a Calc reason from HDC to HDCAD

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
- src/main/resources/application-alt-3-calculation-params.yml
- src/main/resources/application-alt-calculation-params.yml
* Update envs with latest calc params for SDS release SI
> Adjust alt env release parameters

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SDSEarlyReleaseExclusionType.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/SDSEarlyReleaseExclusionForOffenceCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSDSReleaseArrangementLookupService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSDSReleaseArrangementLookupServiceTest.kt
> Add national security and domestic abuse

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
https://dsdmoj.atlassian.net/browse/CRS-2034
> CRS-2034 Set ESL to 0 for FTR(14/28) sentences without a custody date

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/OffenceSDSReleaseArrangementLookupService.kt
Business logic confirmed from ticket
> Use the identical "fourYearsOrMore" function and strip duplicate.

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/enumerations/SDSEarlyReleaseTranche.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheAllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheOne.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheTwo.kt
- src/main/resources/application-alt-3-calculation-params.yml
* Switch the alt and normal envs around so the normal envs have SDS Early Release and alt is for SDS not supported changes
* Sneaky code review comments from CRS-2035 changes that were trivial
> Change alt envs around

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
* Make alt-devs non SDS change to enable testing and progression of other non related tickets
> Turn off SDS unsupported feature in alt envs

- helm_deploy/values-alt-dev.yaml
*Enable on dev-alt for some further testing
> Enable SDS Unsupported on dev-alt

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/DetailedCalculationResults.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/DetailedCalculationResultsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/DetailedCalculationResultsServiceTest.kt
* Update detailed calc results to contain the allocated SDS40 tranche
> CRS-2056 Return SDS40 tranche

- helm_deploy/values-alt-dev.yaml
* Revert alt dev env to as is.
> Revert alt-dev to standard release point

- src/test/resources/test_data/calculation-service-examples.csv
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2063-SDS40-FTR-tused.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2063-SDS40-FTR-tused.json
* Additional RW test scenario for SDS40 with exclusion and FTR
> CRS-2063 Add test to cover initial scenario

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ManualCalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
> Add endpoint for checking if sentence has recalls

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SDSEarlyReleaseDefaultingRulesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/util/BookingHelperTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt
- src/test/resources/test_data/calculation-service-examples.csv
- src/test/resources/test_data/overall_calculation_response/tranches/CRS-2065-Tranche-2-1.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2071-tranche-label-bug-ac1.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2071-tranche-label-bug-ac2.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2071-tranche-label-bug-ac3.json
- src/test/resources/test_data/overall_calculation_response/tranches/over_5_years_after_tranche_1.json
- src/test/resources/test_data/overall_calculation_response/tranches/over_5_years_before_tranche_1.json
- src/test/resources/test_data/overall_calculation_response/tranches/under_5_years_after_tranche_1.json
- src/test/resources/test_data/overall_calculation_response/tranches/under_5_years_before_tranche_1.json
* Update calculation service to explictly calc both variations so other decisions are made easier
* Through correct calc selection the validation issue in CRS-2076 should be resolved
> CRS-2076 and CRS-2074 multiple SDS40 calc changes

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculableSentence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/ConsecutiveSentence.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Hdced4Calculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HdcedCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceAdjustedCalculationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Hdced4CalculatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HdcedCalculatorTest.kt
- src/test/resources/test_data/calculation-service-examples.csv
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2008-ac1.json
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2008-ac2.json
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2008-ac3.json
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2008-ac4.json
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2008-ac5.json
- src/test/resources/test_data/overall_calculation/custom-examples/crs-2008-ac6.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2008-ac1.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2008-ac2.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2008-ac3.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2008-ac4.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2008-ac5.json
- src/test/resources/test_data/overall_calculation_response/custom-examples/crs-2008-ac6.json
Tests and alterations for various scenarios.
> CRS-2008 BOTUS consecutive to SDS and SDS consecutive to BOTUS

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ManualCalculationServiceTest.kt
https://dsdmoj.atlassian.net/browse/CRS-2086
> CRS-2086 - Stop Negative ESL from being saved instead save as 0

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SDSEarlyReleaseDefaultingRulesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Tranche.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheOne.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheTwo.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/main/resources/application-dev.yaml
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SDSEarlyReleaseDefaultingRulesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheAllocationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt
- src/test/resources/test_data/calculation-sds-early-tranching.csv
- src/test/resources/test_data/overall_calculation/tranches/consec-terms-of-imprisonment.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2081-tranche-bug-ex1.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2081-tranche-bug-ex2.json
- src/test/resources/test_data/overall_calculation_response/tranches/CRS-2065-Tranche-1-1.json
- src/test/resources/test_data/overall_calculation_response/tranches/CRS-2065-Tranche-2-2.json
- src/test/resources/test_data/overall_calculation_response/tranches/consec-terms-of-imprisonment.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2081-tranche-bug-ex1.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2081-tranche-bug-ex2.json
- src/test/resources/test_data/overall_calculation_response/tranches/under_5_years_after_tranche_2.json
* Set tranche to 0 when the release date is unaffected
* Ensure that recall sentence length is only considered in the tranche decision if the SLED is on or after T2 commencement date
* Correctly remove term of imprisonment time from tranche calculation
> CRS-2081 Set Tranche to 0 when CRD is unchanged

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Tranche.kt
- src/test/resources/test_data/calculation-sds-early-tranching.csv
- src/test/resources/test_data/overall_calculation/tranches/calc-bug-1.json
- src/test/resources/test_data/overall_calculation/tranches/calc-bug-2.json
- src/test/resources/test_data/overall_calculation/tranches/calc-bug-3.json
- src/test/resources/test_data/overall_calculation_response/tranches/calc-bug-1.json
- src/test/resources/test_data/overall_calculation_response/tranches/calc-bug-2.json
- src/test/resources/test_data/overall_calculation_response/tranches/calc-bug-3.json
* Fix for CRS-2081, minBy is actually minBy or null, so when all the sentences were discounted in the consec sentence, was throwing NPE
> CRS-2081 Fix consec bug

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceValidationTest.kt
Add some logging to the transactional service to clarify fullValidation issue
> Add-logging-to-full-validation

- Dockerfile
Fix a couple of ENV syntax things
> Change to JDK from JRE

- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/resources/test_data/calculation-validation-examples.csv
- src/test/resources/test_data/overall_calculation/validation/CRS-2082.json
- src/test/resources/test_data/overall_calculation_response/validation/CRS-2082.json
* Introduce testing for the validation format
* Add the test files, but don't wire them in  - they'll fail in the pipeline, and I'd like to merge this test framework change
* Small linting and cleanup
> Test framework changes before looking at the issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SDSEarlyReleaseDefaultingRulesService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/Tranche.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheAllocationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheOne.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheTwo.kt
- src/test/resources/test_data/calculation-sds-early-tranching.csv
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-1.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-2.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-3.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-4a.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-4b.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-4c.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2126-ac-5.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-1.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-2.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-3.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-4a.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-4b.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-4c.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2126-ac-5.json
* Filter out any sentences sentenced post T1 from the tranching logic
> CRS-2126 Ensure that only sentences sentenced before T1 are considered for tranching

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingCalculationService.kt
There is already really good coverage for testing the functionality where a consecutive chain has multiple offences, some which are SDS plus and some which aren't. I could add a test case for the prod example. But I'm not sure it really adds anything to our coverage.
> CRS-2019 Reducing the duplicated consecutive sentences.

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationService.kt
Just adding some logging to aid diagnosis of a problem in prod /preprod  that I am unable to reproduce via the TDD tests
> CRS-2135 Add logging to aid diagnosis + small refactor of code

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
* Amend transactional annotations such that calc request can be saved
> Fix bulk comparison

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-alt-preprod.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/FeatureToggles.kt
- src/main/resources/application.yml
Add feature flag to enable and disable future TORERA offence support.
> CRD-2120-torera-feature-flag

- helm_deploy/values-preprod.yaml
Enable TORERA feature on pre-producton
> crs-2132-enable-torera-pre-prod

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HdcedCalculator.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/AdjustmentValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/resources/test_data/overall_calculation/validation/CRS-2165.json
- src/test/resources/test_data/overall_calculation_response/validation/CRS-2165.json
Delete incorrectly added "joel" method
Introduce test case files
> Add logging to sentence length to debug issue

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/exceptions/NoOffenceDatesProvidedException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/PrisonApiProxyController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt
Throw specific exception when no dates on an offence cause calculation to fail
> RCLL-141 Throw specific exception

- .gitignore
- helm_deploy/calculate-release-dates-api/Chart.yaml
- helm_deploy/calculate-release-dates-api/values.yaml
* Update version of data-extractor 
* Specify resources for data-extractor 
* Add helm charts dir to git ignore (when running locally it pulls the dependencies down)
> Update version of data-extractor 

- helm_deploy/values-prod.yaml
as per request now testing on pre-production is complete.
> CRS-torera-enable-production

- helm_deploy/values-prod.yaml
* Turn on manual journey for consec sentences that could affect tranches
> CRS-2149 Turn on in prod

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/SentenceCalculationType.kt
Small change to add the sentence calc type and make it unsupported for now
> CRS-2185 Add STS21 type to SentenceCalc types and make it unsupported

- helm_deploy/values-alt-dev.yaml
- helm_deploy/values-preprod.yaml
* Make feature switch for SDS40 consec manual routing consistent across envs
> Align SDS40 Consec Manual Routing feature switch across envs

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/SentenceCalculation.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/UnadjustedReleaseDate.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/timeline/TimelineCalculationHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/timeline/TimelineSentenceCalculationHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/RecallValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HdcedCalculatorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SDSEarlyReleaseDefaultingRulesServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TrancheAllocationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/util/BookingHelperTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/UnsupportedSDS40RecallSentenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt
- src/test/resources/test_data/calculation-service-examples.csv
- src/test/resources/test_data/overall_calculation/validation/CRS-2207.json
- src/test/resources/test_data/overall_calculation_response/validation/CRS-2207.json
Fixing some issues after the timeline refactor. I've had to re-introduce the historic release date.
> CRS-2207 Unsupported Recall Validation fixes.

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ManualCalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/DateValidationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/DateValidationServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/UnsupportedSDS40RecallSentenceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt
Validate dates for calculation are valid for manual calculation request.
> Crs 2191 validate calculation dates

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculationBreakdown.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/CalculationResult.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationResultEnrichmentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctions.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/timeline/TimelineAdjustmentService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HintTextTest.kt
- src/test/resources/test_data/hint-text.csv
- src/test/resources/test_data/hint-text/expected-results/crs-2212-ac1.json
- src/test/resources/test_data/hint-text/expected-results/crs-2212-ac2.json
- src/test/resources/test_data/hint-text/expected-results/crs-2212-ac3.json
- src/test/resources/test_data/hint-text/expected-results/crs-2212-ac4.json
- src/test/resources/test_data/hint-text/expected-results/crs-2212-ac5.json
- src/test/resources/test_data/hint-text/expected-results/crs-2212-ac6.json
- src/test/resources/test_data/hint-text/expected-results/crs-2263-ac8.json
- src/test/resources/test_data/hint-text/input-data/crs-2263-ac8.json
this is behind a feature toggle (the feature tiggle was added in the preceding ticket CRS-2212)
> CRS-2263 post tranche adjustment hints (following CRS-2212)

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/FeatureToggles.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/FixedTermRecallsService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/RecallValidationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/HintTextTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationServiceTest.kt
Add feature toggle for revised fixed term recall rules.
> CRS-2137-updated-ftr-rules

- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt
Enable revised FTR rules for production environment.
> crs-2137-enable-revised-ftr-rules

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/ControllerAdvice.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/exceptions/NoActiveBookingException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/PrisonApiClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
Create new Exception for No Active Booking. 
Create complementary Handler with no log entries.
> Crs 2289 prevent logging no offences found

- helm_deploy/values-prod.yaml
Corresponding PR to add pre-prod rds secret to prod namespace here: https://github.com/ministryofjustice/cloud-platform-environments/pull/30012
Such that this works i'll manually copy the secret
> CRS-2277 Configure postgresDatabaseRestore job

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingExtractionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/sentence/OraExtraction.kt
Extract deep nested logic from extractConcurrentOraAndNonOraDetails
> Crs 1110 partial refactor booking extraction

- helm_deploy/values-prod.yaml
Enable consec botus on production
> crs-2262-enable-consecutive-botus-prod

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/model/external/SentenceCalculationType.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationIntTest.kt
- src/test/resources/test_data/api_integration/sentences/CRS-2321.json
SEC91_03 and SEC91_03_ORA need the same SDS eligibility rules applied as those for SECTION250.
> crs-2321-sec91-sds-rules

- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationIntTest.kt
- src/test/resources/test_data/api_integration/sentences/CRS-2321-1.json
- src/test/resources/test_data/api_integration/sentences/CRS-2321-2.json
- src/test/resources/test_data/api_integration/sentences/CRS-2321-3.json
- src/test/resources/test_data/api_integration/sentences/CRS-2321-4.json
> crs-2321-additional-tests

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/SentenceCombinationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/util/ConsecutiveSentenceUtil.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ComparisonEventIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationIntTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceValidationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/SentenceValidationServiceTest.kt
Create bespoke validation for bulk calc validation messages in relation to consecutive sentences.
> crs-2353-bulk-calc-validation

- src/test/resources/test_data/calculation-service-examples.csv
- src/test/resources/test_data/overall_calculation/tranches/crs-2329-tranche-bug-test-updated-adjs-1.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2329-tranche-bug-test-updated-adjs-2.json
- src/test/resources/test_data/overall_calculation/tranches/crs-2329-tranche-bug.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2329-tranche-bug-test-updated-adjs-1.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2329-tranche-bug-test-updated-adjs-2.json
- src/test/resources/test_data/overall_calculation_response/tranches/crs-2329-tranche-bug.json
* Original code changes were superseded by later timeline service fixes
* PR adds the real life scenarios with boundary condition adjustments that previously caused a tranche allocation bug.
> CRS-2329 Add real life test scenarios

- openapi-specs/prison-api-docs.json
- src/main/resources/logback-spring.xml
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationReasonControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/CalculationReferenceControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/HistoricCalculationsControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/WorkingDayControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/BookingServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationBreakdownServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/CalculationTransactionalServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/DetailedCalculationResultsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/TransformFunctionsTest.kt
Set flyway logging level to "warn"
Remove real names from test / informational data
Replace MockBean with MockitoBean within affected tests
> flyway-logging-level

- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/container/PostgresContainer.kt
> Increase db connection pool

- helm_deploy/calculate-release-dates-api/Chart.yaml
* PR to test the upgrade to the latest version of data-analytics-extractor
* If this does not successfully run then this PR will need to be reverted prior to any other deployment to prod
> CRS-2368 Update to latest version of data-analytics-extractor

- build.gradle.kts
- helm_deploy/calculate-release-dates-api/values.yaml
- helm_deploy/values-prod.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/config/FeatureToggles.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ImportantDates.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/RecallValidationService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationCode.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/ValidationService.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/validation/RecallValidationServiceTest.kt
Trigger manual journey for FTR 48 affected recalls. Add mockito kotlin test library to help mocking objects.
> crs-2367-ftr48-manual-journey

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/ValidationController.kt
SupportedValidation result in ValidationController to help trace unexpected manual entry triggering
> Add logging

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/eligibility/ErsedEligibilityService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/integration/wiremock/ManageOffencesMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/resource/EligibilityControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/eligibility/ErsedEligibilityServiceTest.kt
Check offence codes from shedule 19ZA part 1 and part 2, instead of only part 1.
> crs-2110-eds-torera-codes

- .circleci/config.yml
- .github/workflows/deploy_to_env.yml
- .github/workflows/pipeline.yml
- helm_deploy/calculate-release-dates-api/values.yaml
- src/main/resources/application.yml
Testing out in dev environment first
> CRS-2399: Initial migration to github actions

- .circleci/config.yml
- .github/workflows/deploy_to_env.yml
- .github/workflows/pipeline.yml
- helm_deploy/calculate-release-dates-api/values.yaml
- src/main/resources/application.yml
Attempt 2, this time setting the k8s_deployment_name to match the nameOverride in the helm values.
> CRS-2399: Move to github actions for dev deployment

- src/main/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ThingsToDoService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/calculatereleasedatesapi/service/ThingsToDoServiceTest.kt
Instead of using the analysed sentences and offences we use a more specific set of conditions and also check return to custody date and fine payments. One of the issues with using analysed sentences and offences is that removed sentences were not detected.
> CRS-2491: Update things to do logic
